services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/config.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.size=256MB
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    ports:
      - 9090:9090
    restart: unless-stopped
  loki:
    image: grafana/loki:3.1.0
    command: -config.file /mnt/config/loki-config.yml
    volumes:
      - ./loki/config.yml:/mnt/config/loki-config.yml
      - loki_data:/loki
    restart: unless-stopped
  tempo:
    image: grafana/tempo:2.5.0
    command: -config.file /mnt/config/tempo-config.yml
    volumes:
      - ./tempo/config.yml:/mnt/config/tempo-config.yml
      - tempo_data:/var/tempo
    restart: unless-stopped
  grafana:
    image: grafana/grafana:11.0.1
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_DEFAULT_THEME=light
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  prometheus_data: {}
  loki_data: {}
  tempo_data: {}
  grafana_data: {}
