POST http://localhost:8080/api/simple-board
Content-Type: application/json

{
  "name": "lee",
  "age": 36
}

###

GET http://localhost:8080/api/simple-board/1
Accept: application/json

###

PUT http://localhost:8080/api/simple-board/1
Content-Type: application/json

{
  "id": 1,
  "name": "lee2",
  "age": 362
}

###

DELETE http://localhost:8080/api/simple-board/1
Content-Type: application/json

###

GET http://localhost:8080/api/simple-board/list
Accept: application/json
