version: '3'
services:
  db:
    image: scaffold-db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - "./db/data:/var/lib/mysql"
    ports:
    - "3306:3306"
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  hoppscotch:
    image: liyasthomas/postwoman:v1.9.9
    ports:
    - "3000:3000"
    environment:
      HOST: 0.0.0.0