# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc-simple.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grpc-simple.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc-simple.proto\x12\ngrpcsimple\")\n\x0b\x44\x61taRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"9\n\x0c\x44\x61taResponse\x12\x15\n\rresultMessage\x18\x01 \x01(\t\x12\x12\n\nresultData\x18\x02 \x01(\x0c\x32N\n\rSimpleService\x12=\n\x08sendData\x12\x17.grpcsimple.DataRequest\x1a\x18.grpcsimple.DataResponseB\x92\x01\n3com.seungyeoplee.poc.communication.grpcsimple.protoB\x0fGrpcSimpleProtoZJgithub.com/seungyeop-lee/poc/communication/grpc-simple/proto/go/grpcsimpleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_simple_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n3com.seungyeoplee.poc.communication.grpcsimple.protoB\017GrpcSimpleProtoZJgithub.com/seungyeop-lee/poc/communication/grpc-simple/proto/go/grpcsimple'
  _globals['_DATAREQUEST']._serialized_start=33
  _globals['_DATAREQUEST']._serialized_end=74
  _globals['_DATARESPONSE']._serialized_start=76
  _globals['_DATARESPONSE']._serialized_end=133
  _globals['_SIMPLESERVICE']._serialized_start=135
  _globals['_SIMPLESERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
