services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    volumes:
      - ./config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "8000:8000"
    networks:
      - mosquitto
    restart: unless-stopped

volumes:
  mosquitto_data: {}
  mosquitto_log: {}

networks:
  mosquitto:
    external: true