version: '3'

services:
  sshd-alpine:
    image: sshd-alpine:latest
    build:
      context: ../sshd-alpine
    container_name: sshd-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.tcp.routers.router-ssh.entrypoints=entryPoint-ssh"
      - "traefik.tcp.routers.router-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.router-ssh.service=service-ssh"
      - "traefik.tcp.services.service-ssh.loadbalancer.server.port=22"
    networks:
      - proxy

networks:
  proxy:
    external: true
