version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10.1
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8022:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/static.yml:/etc/traefik/traefik.yml:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
