import type {Metadata} from "next";
import "./globals.css";
import React, {Suspense} from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Suspense>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
