x-common-part: &common-part
  build:
    context: ./db
    dockerfile: Dockerfile
  volumes:
    - ./db/initdb.d:/docker-entrypoint-initdb.d
    - db-data:/var/lib/mysql
    - db-log:/var/log/mysql
    - db-backup:/backup
  networks:
    - mariabackup
  environment:
    MYSQL_PORT: 3306
    MYSQL_ROOT_PASSWORD: rootPw
    MYSQL_DATABASE: mariadb_backup
    MYSQL_USER: user
    MYSQL_PASSWORD: userPw
    TZ: Asia/Seoul

services:
  db:
    <<: *common-part
    restart: always
    ports:
      - "3307:3306"
  prepare:
    <<: *common-part
    command: >
      mariabackup
      --target-dir=/backup
      --datadir=/var/lib/mysql
      --prepare
  restore:
    <<: *common-part
    command: >
      mariabackup
      --target-dir=/backup
      --copy-back
  debug:
    <<: *common-part
    entrypoint: sleep infinity

volumes:
  db-data:
    name: mariabackup_db-data
  db-log:
    name: mariabackup_db-log
  db-backup:
    name: mariabackup_db-backup

networks:
  mariabackup:
    external: true
