version: '3'

services:
  sshd-alpine:
    image: sshd-alpine:latest
    build:
      context: ./sshd-alpine
    container_name: sshd-alpine
    networks:
      - proxy

networks:
  proxy:
    external: true
