### get code from authorization server
GET http://localhost:8080/oauth2/authorize?response_type=code&client_id=oidc-client&redirect_uri=http://localhost:8000/login/oauth2/code/oidc-client&scope=openid profile

### get token from authorization server
POST http://localhost:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic oidc-client oidc-secret

grant_type=authorization_code&redirect_uri=http://localhost:8000/login/oauth2/code/oidc-client&code=OMqu-w1tKjjfXx-62wU0v2g9AWDjlrDTZzXG1glRZh34nwlzMJt231XqHeC-QFh-xTIxc1dbv-9Lg32WtyLzKMBHVF8xryP18Kt4QPPfI_5G-q89LZ-2qnGFH_-MSwmz

###
GET http://localhost:8080/userinfo
Authorization: Bearer eyJraWQiOiI3ZTc4YThjMy04YTM3LTRlYjItYTI5Yi1kOGY5MjI1M2JiMzAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxMDE0NjAxNTc2MzM3MDc2NDM4MjIiLCJhdWQiOiJvaWRjLWNsaWVudCIsIm5iZiI6MTcxMzEwMTY0Miwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3MTMxMDE5NDIsImlhdCI6MTcxMzEwMTY0MiwianRpIjoiZjNmNDhmZjMtZjYzMi00ZGQ3LTljZmMtNjQ2OGJjNzJkN2I5In0.fILv63hFTQaklaEu9WYb7E8eqmS7eRKX2KvnLMfsUfQ2tu-Odha95UpCGLISthlCLscgFBB-FBZjIG4Rk6Ihh0aUPrq4MWRpSY_b_u9ra4Wp90Pxnkag33hW8uKSG0YUxFNAzpko_V-6vmJZscBtKKISknJxe1zgwSbJov8LhaRIvdy6gUf_ATW9X7Lb2Tv3bpYDMWbmweyEl_lqQBTkxM6aYExAhC8zGilcwk_JTuC4dh_iBuJTrlh-Bc9D_beM55qPJlZAFRJRuxPK7LieH2aIv-uP4ASpqkCA1oQQ8CvWy1IZIqmp6CGZxE3yz_x1fHV2PQurkzUs5GFZgeivag

###
GET http://localhost:8080/oauth2/jwks
Authorization: Bearer eyJraWQiOiI3ZTc4YThjMy04YTM3LTRlYjItYTI5Yi1kOGY5MjI1M2JiMzAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxMDE0NjAxNTc2MzM3MDc2NDM4MjIiLCJhdWQiOiJvaWRjLWNsaWVudCIsIm5iZiI6MTcxMzEwMTY0Miwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3MTMxMDE5NDIsImlhdCI6MTcxMzEwMTY0MiwianRpIjoiZjNmNDhmZjMtZjYzMi00ZGQ3LTljZmMtNjQ2OGJjNzJkN2I5In0.fILv63hFTQaklaEu9WYb7E8eqmS7eRKX2KvnLMfsUfQ2tu-Odha95UpCGLISthlCLscgFBB-FBZjIG4Rk6Ihh0aUPrq4MWRpSY_b_u9ra4Wp90Pxnkag33hW8uKSG0YUxFNAzpko_V-6vmJZscBtKKISknJxe1zgwSbJov8LhaRIvdy6gUf_ATW9X7Lb2Tv3bpYDMWbmweyEl_lqQBTkxM6aYExAhC8zGilcwk_JTuC4dh_iBuJTrlh-Bc9D_beM55qPJlZAFRJRuxPK7LieH2aIv-uP4ASpqkCA1oQQ8CvWy1IZIqmp6CGZxE3yz_x1fHV2PQurkzUs5GFZgeivag
