spring:
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/version1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
