// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package containers

import (
	"github.com/seungyeop-lee/go-scaffold/server/containers/config/database"
	"github.com/seungyeop-lee/go-scaffold/server/internal/aggregates/patron"
	"github.com/seungyeop-lee/go-scaffold/server/internal/commands/patron/sign_in"
	"github.com/seungyeop-lee/go-scaffold/server/internal/handlers/admin/web"
	patron3 "github.com/seungyeop-lee/go-scaffold/server/internal/handlers/admin/web/patron"
	patron2 "github.com/seungyeop-lee/go-scaffold/server/internal/interactors/admin/web/patron"
	"github.com/seungyeop-lee/go-scaffold/server/tools/datasource"
	"github.com/seungyeop-lee/go-scaffold/server/tools/password"
)

// Injectors from wire.go:

func InitAdminWeb() *web.MainHandler {
	repository := patron.NewGormRepository()
	aggregate := patron.NewAggregate(repository)
	db := database.NewGormDB()
	txBeginner := datasource.NewGormTxBeginner(db)
	txWrapper := datasource.NewGormTxWrapper(txBeginner)
	helper := password.NewBcryptHelper()
	command := signIn.NewCommand(aggregate, txWrapper, helper)
	presenter := patron2.NewPresenter()
	controller := patron2.NewController(command, presenter)
	handler := patron3.NewHandler(controller)
	mainHandler := web.NewHandler(handler)
	return mainHandler
}
