services:
  target:
    image: target:green
    build:
      context: ../pochelper/echo
      dockerfile: Dockerfile
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.green.rule=PathPrefix(`/`)"
      - "traefik.http.routers.green.entrypoints=entryPoint-web"
      - "traefik.http.routers.green.service=bluegreen"
      - "traefik.http.routers.green.middlewares=green-retry@docker"
      - "traefik.http.middlewares.green-retry.retry.attempts=4"
      - "traefik.http.middlewares.green-retry.retry.initialinterval=200ms"
      - "traefik.http.services.bluegreen.loadbalancer.server.port=80"
    entrypoint: "/app/echo green"
    networks:
      - proxy

networks:
  proxy:
    external: true
