services:
  server:
    image: docker-sshd:latest
    build:
      context: .
      dockerfile: sshd.Dockerfile
    privileged: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "8022:22"
    volumes:
      - docker-lib:/var/lib/docker
  client:
    image: ssh-client:latest
    build:
      context: .
      dockerfile: sshclient.Dockerfile
    volumes:
      - ./key:/root/key

volumes:
  docker-lib: {}
