create table "public"."currency" (
    "code" text not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."product_price" (
    "id" bigint generated by default as identity not null,
    "price" numeric not null default '0'::numeric,
    "currency_code" text not null default 'KRW'::text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."order" add column "currency_code" text default 'KRW'::text;

alter table "public"."order" alter column "price" drop default;

alter table "public"."order" alter column "price" set data type numeric using "price"::numeric;

alter table "public"."order_product" add column "currency_code" text not null default 'KRW'::text;

alter table "public"."order_product" alter column "price" drop default;

alter table "public"."order_product" alter column "price" set data type numeric using "price"::numeric;

alter table "public"."product" add column "currency_code" text not null default 'KRW'::text;

alter table "public"."product" alter column "price" drop default;

alter table "public"."product" alter column "price" set data type numeric using "price"::numeric;

CREATE UNIQUE INDEX currency_pkey ON public.currency USING btree (code);

CREATE UNIQUE INDEX product_price_pkey ON public.product_price USING btree (id);

alter table "public"."currency" add constraint "currency_pkey" PRIMARY KEY using index "currency_pkey";

alter table "public"."product_price" add constraint "product_price_pkey" PRIMARY KEY using index "product_price_pkey";

alter table "public"."order" add constraint "order_currency_code_fkey" FOREIGN KEY (currency_code) REFERENCES currency(code) not valid;

alter table "public"."order" validate constraint "order_currency_code_fkey";

alter table "public"."order_product" add constraint "order_product_currency_code_fkey" FOREIGN KEY (currency_code) REFERENCES currency(code) not valid;

alter table "public"."order_product" validate constraint "order_product_currency_code_fkey";

alter table "public"."product" add constraint "product_currency_code_fkey" FOREIGN KEY (currency_code) REFERENCES currency(code) not valid;

alter table "public"."product" validate constraint "product_currency_code_fkey";

alter table "public"."product_price" add constraint "product_price_currency_code_fkey" FOREIGN KEY (currency_code) REFERENCES currency(code) not valid;

alter table "public"."product_price" validate constraint "product_price_currency_code_fkey";

grant delete on table "public"."currency" to "anon";

grant insert on table "public"."currency" to "anon";

grant references on table "public"."currency" to "anon";

grant select on table "public"."currency" to "anon";

grant trigger on table "public"."currency" to "anon";

grant truncate on table "public"."currency" to "anon";

grant update on table "public"."currency" to "anon";

grant delete on table "public"."currency" to "authenticated";

grant insert on table "public"."currency" to "authenticated";

grant references on table "public"."currency" to "authenticated";

grant select on table "public"."currency" to "authenticated";

grant trigger on table "public"."currency" to "authenticated";

grant truncate on table "public"."currency" to "authenticated";

grant update on table "public"."currency" to "authenticated";

grant delete on table "public"."currency" to "service_role";

grant insert on table "public"."currency" to "service_role";

grant references on table "public"."currency" to "service_role";

grant select on table "public"."currency" to "service_role";

grant trigger on table "public"."currency" to "service_role";

grant truncate on table "public"."currency" to "service_role";

grant update on table "public"."currency" to "service_role";

grant delete on table "public"."product_price" to "anon";

grant insert on table "public"."product_price" to "anon";

grant references on table "public"."product_price" to "anon";

grant select on table "public"."product_price" to "anon";

grant trigger on table "public"."product_price" to "anon";

grant truncate on table "public"."product_price" to "anon";

grant update on table "public"."product_price" to "anon";

grant delete on table "public"."product_price" to "authenticated";

grant insert on table "public"."product_price" to "authenticated";

grant references on table "public"."product_price" to "authenticated";

grant select on table "public"."product_price" to "authenticated";

grant trigger on table "public"."product_price" to "authenticated";

grant truncate on table "public"."product_price" to "authenticated";

grant update on table "public"."product_price" to "authenticated";

grant delete on table "public"."product_price" to "service_role";

grant insert on table "public"."product_price" to "service_role";

grant references on table "public"."product_price" to "service_role";

grant select on table "public"."product_price" to "service_role";

grant trigger on table "public"."product_price" to "service_role";

grant truncate on table "public"."product_price" to "service_role";

grant update on table "public"."product_price" to "service_role";


