create table "public"."order" (
    "id" bigint generated by default as identity not null,
    "price" bigint not null default '0'::bigint
);


create table "public"."order_product" (
    "id" bigint generated by default as identity not null,
    "quantity" bigint not null default '1'::bigint,
    "price" bigint not null default '0'::bigint,
    "product_id" bigint not null,
    "order_id" bigint not null
);


create table "public"."product" (
    "id" bigint generated by default as identity not null,
    "title" character varying,
    "price" bigint not null default '0'::bigint
);


CREATE UNIQUE INDEX order_pkey ON public."order" USING btree (id);

CREATE UNIQUE INDEX order_product_pkey ON public.order_product USING btree (id);

CREATE UNIQUE INDEX product_pkey ON public.product USING btree (id);

alter table "public"."order" add constraint "order_pkey" PRIMARY KEY using index "order_pkey";

alter table "public"."order_product" add constraint "order_product_pkey" PRIMARY KEY using index "order_product_pkey";

alter table "public"."product" add constraint "product_pkey" PRIMARY KEY using index "product_pkey";

alter table "public"."order_product" add constraint "order_product_order_id_fkey" FOREIGN KEY (order_id) REFERENCES "order"(id) not valid;

alter table "public"."order_product" validate constraint "order_product_order_id_fkey";

alter table "public"."order_product" add constraint "order_product_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) not valid;

alter table "public"."order_product" validate constraint "order_product_product_id_fkey";

grant delete on table "public"."order" to "anon";

grant insert on table "public"."order" to "anon";

grant references on table "public"."order" to "anon";

grant select on table "public"."order" to "anon";

grant trigger on table "public"."order" to "anon";

grant truncate on table "public"."order" to "anon";

grant update on table "public"."order" to "anon";

grant delete on table "public"."order" to "authenticated";

grant insert on table "public"."order" to "authenticated";

grant references on table "public"."order" to "authenticated";

grant select on table "public"."order" to "authenticated";

grant trigger on table "public"."order" to "authenticated";

grant truncate on table "public"."order" to "authenticated";

grant update on table "public"."order" to "authenticated";

grant delete on table "public"."order" to "service_role";

grant insert on table "public"."order" to "service_role";

grant references on table "public"."order" to "service_role";

grant select on table "public"."order" to "service_role";

grant trigger on table "public"."order" to "service_role";

grant truncate on table "public"."order" to "service_role";

grant update on table "public"."order" to "service_role";

grant delete on table "public"."order_product" to "anon";

grant insert on table "public"."order_product" to "anon";

grant references on table "public"."order_product" to "anon";

grant select on table "public"."order_product" to "anon";

grant trigger on table "public"."order_product" to "anon";

grant truncate on table "public"."order_product" to "anon";

grant update on table "public"."order_product" to "anon";

grant delete on table "public"."order_product" to "authenticated";

grant insert on table "public"."order_product" to "authenticated";

grant references on table "public"."order_product" to "authenticated";

grant select on table "public"."order_product" to "authenticated";

grant trigger on table "public"."order_product" to "authenticated";

grant truncate on table "public"."order_product" to "authenticated";

grant update on table "public"."order_product" to "authenticated";

grant delete on table "public"."order_product" to "service_role";

grant insert on table "public"."order_product" to "service_role";

grant references on table "public"."order_product" to "service_role";

grant select on table "public"."order_product" to "service_role";

grant trigger on table "public"."order_product" to "service_role";

grant truncate on table "public"."order_product" to "service_role";

grant update on table "public"."order_product" to "service_role";

grant delete on table "public"."product" to "anon";

grant insert on table "public"."product" to "anon";

grant references on table "public"."product" to "anon";

grant select on table "public"."product" to "anon";

grant trigger on table "public"."product" to "anon";

grant truncate on table "public"."product" to "anon";

grant update on table "public"."product" to "anon";

grant delete on table "public"."product" to "authenticated";

grant insert on table "public"."product" to "authenticated";

grant references on table "public"."product" to "authenticated";

grant select on table "public"."product" to "authenticated";

grant trigger on table "public"."product" to "authenticated";

grant truncate on table "public"."product" to "authenticated";

grant update on table "public"."product" to "authenticated";

grant delete on table "public"."product" to "service_role";

grant insert on table "public"."product" to "service_role";

grant references on table "public"."product" to "service_role";

grant select on table "public"."product" to "service_role";

grant trigger on table "public"."product" to "service_role";

grant truncate on table "public"."product" to "service_role";

grant update on table "public"."product" to "service_role";


