services:
  mediamtx:
    image: bluenviron/mediamtx:1.9.3-ffmpeg-rpi
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    networks:
      - mediamtx
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    environment:
      MTX_PROTOCOLS: tcp
      MTX_WEBRTCADDITIONALHOSTS: ${IP}

networks:
  mediamtx:
    external: true
