AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  serverless-nextjs-demo
  Sample SAM Template for serverless-nextjs-demo

Globals:
  Function:
    Timeout: 10

Resources:
  NextjsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      MemorySize: 256
      PackageType: Image
      Architectures:
        - arm64
      Events:
        RootEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: any
        ProxyEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      DockerTag: v1
      DockerContext: ./app
      Dockerfile: Dockerfile
  NextjsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${NextjsFunction}
      RetentionInDays: 7

Outputs:
  NextjsFunctionURL:
    Description: API Gateway endpoint URL for Next.js
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/
  
  ApiGatewayDomainName:
    Description: API Gateway domain name for CloudFront integration
    Value: !Sub '${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}'
    Export:
      Name: !Sub '${AWS::StackName}:ApiGatewayDomainName'