import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import SideBar from '@/app/(root)/SideBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
    <body>
    <div className="w-dvw h-dvh">
      <div className="flex h-full">
        <SideBar />
        {children}
      </div>
    </div>
    </body>
    </html>
  )
}
