global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: DEBUG
  format: common

accessLog:
  fields:
    names:
      StartUTC: drop

metrics:
  otlp:
    addRoutersLabels: true
    pushInterval: 3s
    grpc:
      endpoint: otel-collector:4317
      insecure: true

tracing:
  otlp:
    grpc:
      endpoint: otel-collector:4317
      insecure: true

entryPoints:
  web:
    address: ":80"
